const comparisonServiceData = {
  basic: [
    { name: "Exterior Wash", included: true },
    { name: "Hand Dry", included: true },
    { name: "Wheel Cleaning", included: false },
    { name: "Undercarriage Wash", included: false },
    { name: "Wax", included: false },
    { name: "Interior Vacuum", included: false },
    { name: "Tire Shine", included: false },
    { name: "Air Freshener", included: false },
    { name: "Dashboard Cleaning", included: false },
    { name: "Mat Cleaning", included: false },
  ],
  standard: [
    { name: "Exterior Wash", included: true },
    { name: "Hand Dry", included: true },
    { name: "Wheel Cleaning", included: true },
    { name: "Undercarriage Wash", included: true },
    { name: "Wax", included: false },
    { name: "Interior Vacuum", included: true },
    { name: "Tire Shine", included: false },
    { name: "Air Freshener", included: true },
    { name: "Dashboard Cleaning", included: false },
    { name: "Mat Cleaning", included: true },
  ],
  premium: [
    { name: "Exterior Wash", included: true },
    { name: "Hand Dry", included: true },
    { name: "Wheel Cleaning", included: true },
    { name: "Undercarriage Wash", included: true },
    { name: "Wax", included: true },
    { name: "Interior Vacuum", included: true },
    { name: "Tire Shine", included: true },
    { name: "Air Freshener", included: true },
    { name: "Dashboard Cleaning", included: true },
    { name: "Mat Cleaning", included: true },
  ],
  deluxe: [
    { name: "Exterior Wash", included: true },
    { name: "Hand Dry", included: true },
    { name: "Wheel Cleaning", included: true },
    { name: "Undercarriage Wash", included: true },
    { name: "Wax", included: true },
    { name: "Interior Vacuum", included: true },
    { name: "Tire Shine", included: true },
    { name: "Air Freshener", included: true },
    { name: "Dashboard Cleaning", included: true },
    { name: "Mat Cleaning", included: true },
  ],
  ultimate: [
    { name: "Exterior Wash", included: true },
    { name: "Hand Dry", included: true },
    { name: "Wheel Cleaning", included: true },
    { name: "Undercarriage Wash", included: true },
    { name: "Wax", included: true },
    { name: "Interior Vacuum", included: true },
    { name: "Tire Shine", included: true },
    { name: "Air Freshener", included: true },
    { name: "Dashboard Cleaning", included: true },
    { name: "Mat Cleaning", included: true },
    { name: "Engine Cleaning", included: true },
    { name: "Headlight Restoration", included: true },
    { name: "Ceramic Coating", included: true },
  ]
};

export default comparisonServiceData;
